# Release Please configuration for GitHub Actions
# See: https://github.com/googleapis/release-please#github-action

name: release-please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.API_ACCESS_GITHUB }}
